In [54]:
# Fundamental package for scientific computing.
# provides multidimensional array object

### Numpy Arrays Vs Python Sequences

In [4]:
#         1.  arrays have fixed size , changing the size will make a new array and delete
#             the previous one
#         2.  elements same datatype (Homogenious) (same memory)
#         3.  advanced mathematical and less code 

### Creating Numpy Arrays

In [ ]:
import numpy as np
# 1d (vector)
arr =np.array([1,2,2])
print(arr)
print(type(arr))

[1 2 2]
<class 'numpy.ndarray'>


In [ ]:
# mulitdimensional
# 2d (matrix)
arr_2d=np.array([[1,2],[4,5]])
print(arr_2d)

[[1 2]
 [4 5]]


In [10]:
# 3d (tensors)
arr_3d =np.array([[[1,2,3],[4,5,6]],[[4,5,3],[6,7,4]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 3]
  [6 7 4]]]


In [12]:
print(np.array([1,2,3],dtype=int))
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1 2 3]
[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [15]:
arr=np.arange(1,10,3)
arr.reshape(3,1)

array([[1],
       [4],
       [7]])

In [19]:
print(np.ones((3,4)))
print(np.zeros((6,5)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
arr =np.random.random((3,4))
print(arr)

[[0.82572758 0.61625762 0.72624387 0.40022105]
 [0.33489972 0.11970078 0.11206937 0.75926229]
 [0.26312686 0.63878796 0.4718343  0.47275159]]


In [25]:
np.linspace(-10,10,9)
# equal distance 9 points b/w (-10,10)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [30]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Attributes

In [42]:
arr =np.arange(10,dtype=np.int16).reshape(5,2)

In [45]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)   # bytes  (2 bit =>1 bytes)
print(arr.dtype)

2
(5, 2)
10
2
int16


In [53]:
# astype
arr=np.array([1,2,3],dtype=int)
print(arr.dtype)
# but if it's like age (that doesn't need float or int64)
arr_new=arr.astype(np.int32)
print(arr_new.dtype)

int64
int32


### Array Operations

In [58]:
arr=np.arange(12).reshape(3,4)
arr_2=np.arange(12,24).reshape(3,4)

In [67]:
print(arr+arr_2)
print("\n",arr+2)
print("\n",arr*2)
print("\n",arr**2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [71]:
# vector operations
print(arr/arr_2)

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [72]:
arr ==10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

### Array Functions

In [87]:
arr =np.random.random((3,4))
arr =np.round(arr*100)
arr

array([[ 4., 91., 28.,  6.],
       [43., 12., 31., 54.],
       [ 1., 25., 98.,  7.]])

In [88]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.prod(arr))

98.0
1.0
400.0
905899343731200.0


In [89]:
# 0 => col
# 1 => row
print(np.max(arr,axis=0))

[43. 91. 98. 54.]


In [90]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

33.333333333333336
26.5
31.533932341033662
994.3888888888888


In [91]:
np.sin(arr)

array([[-0.7568025 ,  0.10598751,  0.27090579, -0.2794155 ],
       [-0.83177474, -0.53657292, -0.40403765, -0.55878905],
       [ 0.84147098, -0.13235175, -0.57338187,  0.6569866 ]])

In [93]:
# dot product
dot=np.dot(arr,arr.copy().reshape(4,3))
print(dot)

[[ 1580.  6377.  1274.]
 [ 2555. 11395.  1757.]
 [ 3367.  7144.   475.]]


In [97]:
print(np.log(arr))
print()
print(np.exp(arr))

[[1.38629436 4.51085951 3.33220451 1.79175947]
 [3.76120012 2.48490665 3.4339872  3.98898405]
 [0.         3.21887582 4.58496748 1.94591015]]

[[5.45981500e+01 3.31740010e+39 1.44625706e+12 4.03428793e+02]
 [4.72783947e+18 1.62754791e+05 2.90488497e+13 2.83075330e+23]
 [2.71828183e+00 7.20048993e+10 3.63797095e+42 1.09663316e+03]]


In [103]:
# round (nearest integer)
# floor (integer less than)
# ceil (integer greater than)
arr=np.random.random(10)*100
print(arr)
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[41.64613623 72.10718171 77.53497821 68.10852157 26.79364249 38.28866057
 78.83580327 93.82060763  8.57597861 38.63763672]
[42. 72. 78. 68. 27. 38. 79. 94.  9. 39.]
[41. 72. 77. 68. 26. 38. 78. 93.  8. 38.]
[42. 73. 78. 69. 27. 39. 79. 94.  9. 39.]


### Indexing and Slicing

In [114]:
arr_1d=np.arange(10)
arr_2d=np.arange(10).reshape(2,5)
arr_3d=np.arange(20).reshape(2,2,5)
print("1D Array :",arr_1d)
print("\n2D Array :",arr_2d)
print("\n3D Array :",arr_3d)

1D Array : [0 1 2 3 4 5 6 7 8 9]

2D Array : [[0 1 2 3 4]
 [5 6 7 8 9]]

3D Array : [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [129]:
# Indexing
print(arr_1d[-1])
print(arr_2d[-1])
print(arr_3d[-1])

print()

print(arr_2d[1,1])
print(arr_3d[1,0,3])

9
[5 6 7 8 9]
[[10 11 12 13 14]
 [15 16 17 18 19]]

6
13


In [134]:
# Slicing
print(arr_1d[2:5:2])
print(arr_2d[2:5])
print(arr_3d[2:5])

print()

print(arr_2d[:,3:])
print(arr_3d[:,1:,1:4])


# all corners
print("\nall corners :",arr_2d[:,::4])

[2 4]
[]
[]

[[3 4]
 [8 9]]
[[[ 6  7  8]]

 [[16 17 18]]]

all corners : [[0 4]
 [5 9]]


### Iterating

In [136]:
for i in arr_3d:
    print(i)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [138]:
for i in np.nditer(arr_3d):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Reshaping

In [146]:
print(arr_2d)
print()
print("Transpose of a matrix :",np.transpose(arr_2d))

[[0 1 2 3 4]
 [5 6 7 8 9]]

Transpose of a matrix : [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [153]:
# .reshape()
print(arr_3d)
print()
print("Transpose of a tensor :",np.transpose(arr_3d))

# Visualize tensor as 2d matrix plates on top of another making 3d cube
# then transpose :
                #  just watch this cube from left side
arr2_3d=np.arange(27).reshape((3,3,3))
print()
print()
print(arr2_3d)
print("Transpose of a tensor :",np.transpose(arr2_3d))
# print("Transpose of a tensor :",arr2_3d.T)         # easier way to transpose



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Transpose of a tensor : [[[ 0 10]
  [ 5 15]]

 [[ 1 11]
  [ 6 16]]

 [[ 2 12]
  [ 7 17]]

 [[ 3 13]
  [ 8 18]]

 [[ 4 14]
  [ 9 19]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Transpose of a tensor : [[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [155]:
# ravel    (makes linear)
arr_2d.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Stacking