In [1]:
# Fundamental package for scientific computing.
# provides multidimensional array object

## First Session (PART - I)

### Numpy Arrays Vs Python Sequences

In [2]:
#         1.  arrays have fixed size , changing the size will make a new array and delete
#             the previous one
#         2.  elements same datatype (Homogenious) (same memory)
#         3.  advanced mathematical and less code 

### Creating Numpy Arrays

In [3]:
import numpy as np
# 1d (vector)
arr =np.array([1,2,2])
print(arr)
print(type(arr))

[1 2 2]
<class 'numpy.ndarray'>


In [4]:
# mulitdimensional
# 2d (matrix)
arr_2d=np.array([[1,2],[4,5]])
print(arr_2d)

[[1 2]
 [4 5]]


In [5]:
# 3d (tensors)
arr_3d =np.array([[[1,2,3],[4,5,6]],[[4,5,3],[6,7,4]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 3]
  [6 7 4]]]


In [6]:
print(np.array([1,2,3],dtype=int))
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1 2 3]
[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [7]:
arr=np.arange(1,10,3)
arr.reshape(3,1)

array([[1],
       [4],
       [7]])

In [8]:
print(np.ones((3,4)))
print(np.zeros((6,5)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
arr =np.random.random((3,4))
print(arr)

[[8.68119524e-01 8.25811724e-01 1.68936451e-02 2.73265239e-01]
 [5.99829072e-04 6.81862679e-01 7.51244286e-01 8.65311018e-01]
 [8.15389001e-01 3.98737117e-01 9.07299582e-01 5.74513818e-01]]


In [10]:
np.linspace(-10,10,9)
# equal distance 9 points b/w (-10,10)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [11]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Attributes

In [12]:
arr =np.arange(10,dtype=np.int16).reshape(5,2)

In [13]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)   # bytes  (2 bit =>1 bytes)
print(arr.dtype)

2
(5, 2)
10
2
int16


In [14]:
# astype
arr=np.array([1,2,3],dtype=int)
print(arr.dtype)
# but if it's like age (that doesn't need float or int64)
arr_new=arr.astype(np.int32)
print(arr_new.dtype)

int64
int32


### Array Operations

In [15]:
arr=np.arange(12).reshape(3,4)
arr_2=np.arange(12,24).reshape(3,4)

In [16]:
print(arr+arr_2)
print("\n",arr+2)
print("\n",arr*2)
print("\n",arr**2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [17]:
# vector operations
print(arr/arr_2)

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [18]:
arr ==10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

### Array Functions

In [19]:
arr =np.random.random((3,4))
arr =np.round(arr*100)
arr

array([[86., 34., 89.,  5.],
       [69., 83., 17., 31.],
       [50., 17., 32., 37.]])

In [20]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.prod(arr))

89.0
5.0
550.0
3.952262718410208e+18


In [21]:
# 0 => col
# 1 => row
print(np.max(arr,axis=0))

[86. 83. 89. 37.]


In [22]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

45.833333333333336
35.5
27.94588023702639
780.9722222222222


In [23]:
np.sin(arr)

array([[-0.92345845,  0.52908269,  0.86006941, -0.95892427],
       [-0.11478481,  0.96836446, -0.96139749, -0.40403765],
       [-0.26237485, -0.96139749,  0.55142668, -0.64353813]])

In [24]:
# dot product
dot=np.dot(arr,arr.copy().reshape(4,3))
print(dot)

[[ 9164.  8189. 15111.]
 [ 7165.  9592. 15027.]
 [ 5558.  5049.  8830.]]


In [25]:
print(np.log(arr))
print()
print(np.exp(arr))

[[4.4543473  3.52636052 4.48863637 1.60943791]
 [4.2341065  4.41884061 2.83321334 3.4339872 ]
 [3.91202301 2.83321334 3.4657359  3.61091791]]

[[2.23524660e+37 5.83461743e+14 4.48961282e+38 1.48413159e+02]
 [9.25378173e+29 1.11286375e+36 2.41549528e+07 2.90488497e+13]
 [5.18470553e+21 2.41549528e+07 7.89629602e+13 1.17191424e+16]]


In [26]:
# round (nearest integer)
# floor (integer less than)
# ceil (integer greater than)
arr=np.random.random(10)*100
print(arr)
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[72.55147592 90.06832456  8.19468316 34.80799749 77.10014963 49.06997706
 66.48460389 29.78058005 51.0171105  53.84484163]
[73. 90.  8. 35. 77. 49. 66. 30. 51. 54.]
[72. 90.  8. 34. 77. 49. 66. 29. 51. 53.]
[73. 91.  9. 35. 78. 50. 67. 30. 52. 54.]


### Indexing and Slicing

In [27]:
arr_1d=np.arange(10)
arr_2d=np.arange(10).reshape(2,5)
arr_3d=np.arange(20).reshape(2,2,5)
print("1D Array :",arr_1d)
print("\n2D Array :",arr_2d)
print("\n3D Array :",arr_3d)

1D Array : [0 1 2 3 4 5 6 7 8 9]

2D Array : [[0 1 2 3 4]
 [5 6 7 8 9]]

3D Array : [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [28]:
# Indexing
print(arr_1d[-1])
print(arr_2d[-1])
print(arr_3d[-1])

print()

print(arr_2d[1,1])
print(arr_3d[1,0,3])

9
[5 6 7 8 9]
[[10 11 12 13 14]
 [15 16 17 18 19]]

6
13


In [29]:
# Slicing
print(arr_1d[2:5:2])
print(arr_2d[2:5])
print(arr_3d[2:5])

print()

print(arr_2d[:,3:])
print(arr_3d[:,1:,1:4])


# all corners
print("\nall corners :",arr_2d[:,::4])

[2 4]
[]
[]

[[3 4]
 [8 9]]
[[[ 6  7  8]]

 [[16 17 18]]]

all corners : [[0 4]
 [5 9]]


### Iterating

In [30]:
for i in arr_3d:
    print(i)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
for i in np.nditer(arr_3d):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Reshaping

In [32]:
print(arr_2d)
print()
print("Transpose of a matrix :",np.transpose(arr_2d))

[[0 1 2 3 4]
 [5 6 7 8 9]]

Transpose of a matrix : [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [33]:
# .reshape()
print(arr_3d)
print()
print("Transpose of a tensor :",np.transpose(arr_3d))

# Visualize tensor as 2d matrix plates on top of another making 3d cube
# then transpose :
                #  just watch this cube from left side
arr2_3d=np.arange(27).reshape((3,3,3))
print()
print()
print(arr2_3d)
print("Transpose of a tensor :",np.transpose(arr2_3d))
# print("Transpose of a tensor :",arr2_3d.T)         # easier way to transpose



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Transpose of a tensor : [[[ 0 10]
  [ 5 15]]

 [[ 1 11]
  [ 6 16]]

 [[ 2 12]
  [ 7 17]]

 [[ 3 13]
  [ 8 18]]

 [[ 4 14]
  [ 9 19]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Transpose of a tensor : [[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [34]:
# ravel    (makes linear)
arr_2d.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Stacking

In [35]:
arr1=np.arange(12).reshape((3,4))
arr2=np.arange(12,24).reshape((3,4))
print(arr1)
print()
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
print(np.hstack((arr1,arr2)))
print()
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Spliting

In [37]:
print(np.hsplit(arr1,2))
print()
print(np.vsplit(arr1,3))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## Second Session (PART -II)

### Numpy Array Vs Lists

In [38]:
# Time Difference

import time
start=time.time()
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]
for i in range(10000000):
    c.append(a[i]+b[i])
end=time.time()
print(f"Time taken in List         : {end-start:.2f} Seconds")

start=time.time()
arr_a=np.arange(10000000)
arr_b=np.arange(10000000,20000000)

arr_c=arr_a+arr_b
end=time.time()
print(f"Time taken in Numpy Arrays : {end-start:.2f} Seconds")

Time taken in List         : 2.90 Seconds
Time taken in Numpy Arrays : 0.08 Seconds


In [39]:
# Memory Difference

import sys

a=[i for i in range(10000000)]
print(f"Size :{sys.getsizeof(a)}")

arr=np.arange(10000000,dtype=np.int16)
print(f"Size :{sys.getsizeof(arr)}")

Size :89095160
Size :20000112


### Advanced Indexing

In [ ]:
# Fancy Indexing
print(arr_2d)
print()
arr_2d=np.vstack((arr_2d,arr_2d,arr_2d))
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [44]:
print(arr_2d[[0,2,5]])
print()
print(arr_2d[:,[0,2,3]])

[[0 1 2 3 4]
 [0 1 2 3 4]
 [5 6 7 8 9]]

[[0 2 3]
 [5 7 8]
 [0 2 3]
 [5 7 8]
 [0 2 3]
 [5 7 8]]


In [51]:
# Boolean Indexing

a=np.random.randint(1,100,24).reshape(6,4)
print(a)

[[28 16 20 26]
 [25 80  7 38]
 [25  4 37  2]
 [56 43 87 53]
 [44 25 36 23]
 [11 35 46 17]]


In [56]:
# find all numbers >50
print(a>50)               # Relational Operations
print()
print(a[a>50])            # Boolean Mask

[[False False False False]
 [False  True False False]
 [False False False False]
 [ True False  True  True]
 [False False False False]
 [False False False False]]

[80 56 87 53]


In [60]:
b=(a>50) & (a%2==0)      # & bitwise operator , and => logical operator   (~ => not operator)
print(a[b])

[80 56]


### BroadCasting