In [54]:
# Fundamental package for scientific computing.
# provides multidimensional array object

### Numpy Arrays Vs Python Sequences

In [4]:
#         1.  arrays have fixed size , changing the size will make a new array and delete
#             the previous one
#         2.  elements same datatype (Homogenious) (same memory)
#         3.  advanced mathematical and less code 

### Creating Numpy Arrays

In [ ]:
import numpy as np
# 1d (vector)
arr =np.array([1,2,2])
print(arr)
print(type(arr))

[1 2 2]
<class 'numpy.ndarray'>


In [ ]:
# mulitdimensional
# 2d (matrix)
arr_2d=np.array([[1,2],[4,5]])
print(arr_2d)

[[1 2]
 [4 5]]


In [10]:
# 3d (tensors)
arr_3d =np.array([[[1,2,3],[4,5,6]],[[4,5,3],[6,7,4]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 3]
  [6 7 4]]]


In [12]:
print(np.array([1,2,3],dtype=int))
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1 2 3]
[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [15]:
arr=np.arange(1,10,3)
arr.reshape(3,1)

array([[1],
       [4],
       [7]])

In [19]:
print(np.ones((3,4)))
print(np.zeros((6,5)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
arr =np.random.random((3,4))
print(arr)

[[0.82572758 0.61625762 0.72624387 0.40022105]
 [0.33489972 0.11970078 0.11206937 0.75926229]
 [0.26312686 0.63878796 0.4718343  0.47275159]]


In [25]:
np.linspace(-10,10,9)
# equal distance 9 points b/w (-10,10)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [30]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Attributes

In [42]:
arr =np.arange(10,dtype=np.int16).reshape(5,2)

In [45]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)   # bytes  (2 bit =>1 bytes)
print(arr.dtype)

2
(5, 2)
10
2
int16


In [53]:
# astype
arr=np.array([1,2,3],dtype=int)
print(arr.dtype)
# but if it's like age (that doesn't need float or int64)
arr_new=arr.astype(np.int32)
print(arr_new.dtype)

int64
int32


### Array Operations